module.exports = {
  ANNOTATION_RECEIVED: "ANNOTATION_RECEIVED",
  ANNOTATIONS_RECEIVED: "ANNOTATIONS_RECEIVED",
  ANNOTATION_REMOVED: "ANNOTATION_REMOVED",
  STORE_TEMP_ANNOTATION: "STORE_TEMP_ANNOTATION",
  CLEAR_TEMP_ANNOTATION: "CLEAR_TEMP_ANNOTATION"
};
