module.exports = {
  ANNOTATION_COMMENT_RECEIVED: "ANNOTATION_COMMENT_RECEIVED",
  SONG_COMMENT_RECEIVED: "SONG_COMMENT_RECEIVED",
  ANNOTATION_COMMENT_REMOVED: "ANNOTATION_COMMENT_REMOVED",
  SONG_COMMENT_REMOVED: "SONG_COMMENT_REMOVED"
}
